#!/bin/bash

LABNO="X/sort"
C_EXERCISES="1"
ASM_EXERCISES="1"

GRADINGDIR=.
SAMPLESDIR=/home/porter/comp411/samples/lab$LABNO

ERRORFILE=ERROR

CC_FLAGS="-std=c99"
CC_LIBS="-lm"
DIFF_FLAGS="-bB"
MARS_PATH=/home/porter/comp411/bin/Mars4_5.jar
MARS_FLAGS="nc mc CompactDataAtZero"
TIMEOUT="/usr/bin/timeout --signal=9 10"
set +o noclobber

echo -e "Quickly checking your work ...\n\n"

if [ "$C_EXERCISES" != "NONE" ]; then
  for x in $C_EXERCISES; do
    if [ ! -f ex${x}.c ]; then
      echo -e "\n" "COULD NOT FIND" ex${x}.c "\n\n"
      continue
    fi

    gcc $CC_FLAGS ex${x}.c -o ex${x} $CC_LIBS 2>/dev/null

    if [ $? -ne 0 ]; then
      echo -e "\n\nCOMPILE FAILED for" ex${x}.c
      echo -e "Be sure your program compiles properly; otherwise you will receive zero points."
      echo -e "Command used for compiling was:" gcc $CC_FLAGS ex${x}.c -o ex${x} $CC_LIBS "\n\n"
      continue
    fi

    for infile in $SAMPLESDIR/ex${x}in?; do
      resultfile=`basename $infile | sed s/in/result/g`_C
      outfile=`basename $infile | sed s/in/out/g`
      $TIMEOUT ./ex${x} < $infile > $resultfile
      diff $DIFF_FLAGS -qs $SAMPLESDIR/$outfile $resultfile ||
        (echo -e MISMATCH in $SAMPLESDIR/$outfile AND $resultfile, see $ERRORFILE.$resultfile.txt for diff output... "\n"
         diff $DIFF_FLAGS $SAMPLESDIR/$outfile $resultfile > $ERRORFILE.$resultfile.txt
         diff $DIFF_FLAGS -bB -q $SAMPLESDIR/$outfile $resultfile > /dev/null 2>&1 && echo -e "Seems like a white space mismatch...\n")
    done
  done
fi


if [ "$ASM_EXERCISES" != "NONE" ]; then
  for x in $ASM_EXERCISES; do
    if [ ! -f ex${x}.asm ]; then
      echo -e "\n" "COULD NOT FIND" ex${x}.asm "\n\n"
      continue
    fi

    for infile in $SAMPLESDIR/ex${x}in?; do
      resultfile=`basename $infile | sed s/in/result/g`_ASM
      outfile=`basename $infile | sed s/in/out/g`
      $TIMEOUT java -jar $MARS_PATH $MARS_FLAGS ex${x}.asm < $infile > $resultfile
      diff $DIFF_FLAGS -qs $SAMPLESDIR/$outfile $resultfile ||
        (echo -e MISMATCH in $SAMPLESDIR/$outfile AND $resultfile, see $ERRORFILE.$resultfile.txt for diff output... "\n"
         diff $DIFF_FLAGS $SAMPLESDIR/$outfile $resultfile > $ERRORFILE.$resultfile.txt
         diff $DIFF_FLAGS -bB -q $SAMPLESDIR/$outfile $resultfile > /dev/null 2>&1 && echo -e "Seems like a white space mismatch...\n")
    done
  done
fi

if [ "$WARNSUBMIT" != "NO" ]; then
  echo -e "\n\nREMEMBER THIS IS ONLY A CHECKER SCRIPT!!  TO SUBMIT YOUR WORK, PLEASE RUN SUBMIT SCRIPT.\n"
fi

